server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:smartshelfx}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Sarya_12}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.springframework.security: INFO
    com.smartshelfx: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:4a0e1700413233035bf612656e90923735ff135542e324c84b104a06b94a9a26ce2f4b8f6ca83d5f447d26f14e5f830e02016019c75f6ce906eaec59e2ed7871}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}

seed:
  admin-email: ${SEED_ADMIN_EMAIL:admin@gmail.com}
  admin-password: ${SEED_ADMIN_PASSWORD:123456789}
  admin-name: ${SEED_ADMIN_NAME:admin}
  default-warehouses:
    BLR: Bangalore Central Warehouse
    MUM: Mumbai Hub
